import {
  BASE_URL,
  GOOGLE_CLIENT_ID_ANDROID,
  GOOGLE_CLIENT_ID_IOS,
  FACEBOOK_CLIENT_ID,
  APPLE_CLIENT_ID,
} from '@env'

export const env = {
  BASE_URL: BASE_URL as string,
  GOOGLE_CLIENT_ID_ANDROID: GOOGLE_CLIENT_ID_ANDROID as string,
  GOOGLE_CLIENT_ID_IOS: GOOGLE_CLIENT_ID_IOS as string,
  FACEBOOK_CLIENT_ID: FACEBOOK_CLIENT_ID as string,
  APPLE_CLIENT_ID: APPLE_CLIENT_ID as string,
}
